name: Linux AppImage Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev
        
    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@latest
      
    - name: Install frontend dependencies
      run: |
        cd web
        npm ci
        
    - name: Build frontend
      run: |
        cd web
        npm run build
        
    - name: Build Tauri app
      run: |
        cd src-tauri
        cargo build --release --target ${{ matrix.target }}
        
    - name: Build Linux installer
      run: |
        cd src-tauri
        cargo tauri build --target ${{ matrix.target }}
        
    - name: List build outputs
      run: |
        echo "=== Build output structure ==="
        find src-tauri/target -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" | head -20
        echo "=== Bundle directory contents ==="
        ls -la src-tauri/target/${{ matrix.target }}/release/bundle/ || echo "Bundle directory not found"
        echo "=== Release directory contents ==="
        ls -la src-tauri/target/${{ matrix.target }}/release/ || echo "Release directory not found"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.target }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          src-tauri/target/${{ matrix.target }}/release/*.AppImage
          src-tauri/target/${{ matrix.target }}/release/*.deb
          src-tauri/target/${{ matrix.target }}/release/*.rpm
        retention-days: 30
