name: macOS DMG (ad-hoc)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # Build web application using root package.json scripts
      - name: Build web (prod)
        run: |
          npm ci
          npm run build:web

      - name: Build Tauri DMG (ad-hoc)
        uses: tauri-apps/tauri-action@v0
        env:
          APPLE_SIGNING_IDENTITY: "-"
        with:
          args: --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-${{ matrix.target }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
            src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.app
            src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.tar.gz
