name: Windows MSI/NSIS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Install Tauri CLI
      run: |
        echo "Installing Tauri CLI via cargo..."
        cargo install tauri-cli --version ^2.0
        echo "Tauri CLI installed, checking version..."
        $env:PATH += ";$env:USERPROFILE\.cargo\bin"
        cargo tauri --version
      shell: pwsh
      
    - name: Install frontend dependencies
      run: |
        cd web
        npm ci
        
    - name: Build frontend
      run: |
        cd web
        npm run build
        
    - name: Build Windows installer
      run: |
        $env:PATH += ";$env:USERPROFILE\.cargo\bin"
        npm run tauri build -- --target ${{ matrix.target }}
      shell: pwsh
        
    - name: List build outputs
      run: |
        echo "=== Build output structure ==="
        find src-tauri/target -name "*.msi" -o -name "*.exe" -o -name "*.zip" | head -20
        echo "=== Bundle directory contents ==="
        ls -la src-tauri/target/${{ matrix.target }}/release/bundle/ || echo "Bundle directory not found"
        echo "=== All target directories ==="
        ls -la src-tauri/target/ || echo "Target directory not found"
        echo "=== Release directory contents ==="
        ls -la src-tauri/target/${{ matrix.target }}/release/ || echo "Release directory not found"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.target }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          src-tauri/target/${{ matrix.target }}/release/*.exe
          src-tauri/target/${{ matrix.target }}/release/*.msi
        retention-days: 30
